<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    public function getForUser($dbh,$userId)
    {
	$requete = 'SELECT site_id FROM user_site WHERE user_id = '.$userId;
    }

    public function findAll()
    {
        return $this->findBy(array(), array('affaire' => 'ASC'));
    }
}
